### ISSUE TITLE
Support Vaadin 8

### ISSUE THREAD

**Issue by ajay9640** [bdunn44/MEJS-Vaadin#12]
MediaElement.js  addon is working fine with vaadin 7.7.3. But, when I try to use this in vaadin8.1.0 
getting the exception java.lang.NoSuchMethodError: com.kbdunn.vaadin.addons.mediaelement.MediaElementPlayer.addAttachListener(Lcom/vaadin/server/ClientConnector$AttachListener;).

Can you please tell me a how to make it compatible with vaadin 8? Or R u going to realease new version which is compatible to vaadin 8?
